### PR TITLE
Some small interface updates to the application

### PR DESCRIPTION
**Pull request by IAPark**
Just as I was looking around and there were a few things I noticed that I thought needed changed. I recognize the interface is not yet final, but I assume the final version will be an edited version of the current.

I have also have another thing that I feel needs done: we need a text field when someone selects other as a dietary restriction. I'll try to submit a pull request to do that in a bit.

We will also want to add links for the documents the user has to agree to. We can't do it for our agreement yet, because I assume we don't have one, but linking to MLH's site is probably best anyway.

### CODE REVIEW

**Comment by IAPark** [comment]
Oh and one other thing. Is there any easy way to add an admin right now? I did it using the Mongo shell, but it wasn't the easiest process. Maybe it should be part of the config?

**Comment by pdilyard** [comment]
Thanks for doing that. Yeah the form for application that is currently there is really only for testing. The way the form looks and the links that it has are definitely going to change.

As far as the admin goes, throwing an admin email address into the config file would be a good idea. If you decide to do it, be sure to put it in config_example.js, as that's the only config checked into the repo.

**Comment by pdilyard** [comment]
Btw, I probably won't be merging these until the weekend.

**Comment by pdilyard** [comment]
One more thing to note on my near future plans:

I'm going to be pulling the Angular app out into it's own repository, to make it easier for future leaders to edit it without messing with the API.

I'm also going to be changing up the way the API works, and making it a lot more RESTful. The tickets and messages modules are good examples of how the API is going to look across the board soon.

**Comment by IAPark** [comment]
I was wonder about that. I really through me that the api and the interface were both part of the same node.js app, I assume most everything would work just being launched as a normal static site, but some of the imports (socket.io) didn’t link up to a real file. Anyway other than that there are a few notes I’d like to add to the read me such as bower and the above.

**Comment by pdilyard** [comment]
And just in general:

If you could follow these rules for commit names:
- Action tense (e.g. Add link to MLH Code of Conduct)
- First letter capitalized
- Any additional information about commits in bullet points on new lines underneath the main part of the message

I know this sounds particular but I'm particular :)

**Comment by pdilyard** [comment]
You can hold off on adding anything to the README for now. When I move repositories, I'll be sure to give the Angular app it's own instructions.

The Angular app will mostly work on it's own, but in it's production environment, it will need to be on a web server for things like routing without the hashbang (site.com/application instead of site.com/#/application).

To answer your question about socket.io, it's actually pulling the client-side socket.io library from the server.

**Pull request merged**
